title: Agave School Example
email: agave-school@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
source: "src"
destination: "../build"

# Build settings
markdown: kramdown

plugins:
  - octopress-paginate

exclude:
  - node_modules

collections:
  posts:
    output: true
    permalink: /post/:path/
  communications:
    output: true
    permalink: /communication/:path/
  services:
    output: true
    permalink: /service/:path/
